version: '3'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: ["start-dev"]
  spring:
    build: .
    ports:
      - "8088:8088"
  nodejs:
    build: D:\Spring\CV_Project\cvproject-ui
    ports:
      - "3000:80"
  db:
    image: mysql:8.3.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: cvproject
    restart: always
  mail:
    build: D:\Spring\CV_Project\Mail
    ports:
      - "8089:8089"