server:
  port: 8088

fe:
base-url: http://localhost:3000

keycloak:
  base-url: http://localhost:8080/realms/cvproject/protocol/openid-connect/token/introspect
  realm: cvproject
  client-id: react-auth
  client-secret: oLTNsGCxnKA6mPxcmnQuEuHApBi5x9Jo