server:
  port: 8088

fe:
#  base-url: http://localhost:3000
  #  Cong Huy config
  base-url: http://localhost:3001

keycloak:
  #  base-url: http://localhost:8080/realms/cvproject/protocol/openid-connect/token/introspect
  #  realm: test
  #  client-id: test
  #  client-secret: XZFD3f6K87mYWJRD36Ug0zfg4YAmEhEi

  #Cong Huy config
  base-url: http://localhost:8080/realms/cvproject/protocol/openid-connect/token/introspect
  realm: cvproject
  client-id: react-auth
  client-secret: oLTNsGCxnKA6mPxcmnQuEuHApBi5x9Jo
api:
  prefix: api
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cvproject
    #url: jdbc:mysql://localhost:3306/ShopApp?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    #password:
    password: 123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher