server:
  port: 8088

fe:
  #  base-url: http://localhost:3000
  #  Cong Huy config
  base-url: http://localhost:3001

keycloak:
  #  base-url: http://localhost:8080/realms/cvproject/protocol/openid-connect/token/introspect
  #  realm: test
  #  client-id: test
  #  client-secret: XZFD3f6K87mYWJRD36Ug0zfg4YAmEhEi

  #Cong Huy config
  base-url: http://localhost:8080/realms/cvproject/protocol/openid-connect/token/introspect
  realm: cvproject
  client-id: react-auth
  client-secret: oLTNsGCxnKA6mPxcmnQuEuHApBi5x9Jo
api:
  prefix: api
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tetsdb
    #url: jdbc:mysql://localhost:3306/cvproject
    #url: jdbc:mysql://localhost:3306/ShopApp?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    root: INFO
  pattern:
    console: "%clr(%d{yyyy-MM-dd E HH:mm:ss}){cyan} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr(:){faint} %m%n%clr(${LOG_EXCEPTION_CONVERSION_WORD:%wEx}){red}"